name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions:
  contents: write
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    concurrency: ci-${{ github.ref }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    strategy:
      matrix:
        node-version: [18.x] 

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: staring Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: install dependencies
      run: npm ci
    - name: build production project
      run: npm run build:prod
      if: always()
    - name: run eslint
      run: npm run lint
      if: always()
    - name: run stylelint
      run: npm run stylelint
      if: always()
    - name: run unit tests
      run: npm run test:unit
      if: always()
    # - name: publish to Chromatic
    #   uses: chromaui/action@v1
    #   with:
    #     projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
    #     exitZeroOnChanges: false
    - name: setup pages
      uses: actions/configure-pages@v2
      if: always()
    - name: upload artifact
      uses: actions/upload-pages-artifact@v1
      if: always()
      with:
        path: 'reports/unit/report.html'
    - name: deploy to GitHub Pages
      id: deployment
      if: always()
      uses: actions/deploy-pages@v1

